### ISSUE TITLE
A series of bugs discovered on Gitpod

### ISSUE THREAD

**Issue by im-coder-lg** [kimlimjustin/xplorer#146]
### Description

So, I noticed the recent merge on Xplorer(commit hash: d9e451051bd8defe555045f17d038700a6ef7b3f) and wanted to check it out, so I popped up a Gitpod Workspace. First off, there is some sort of speed with Gitpod that it misses out `yarn` and the second one is that for Docusaurus, it throws out this error:
```console
$ yarn start
yarn run v1.22.11
$ docusaurus start
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module './util/canReportError'
Require stack:
- /workspace/xplorer/docs/node_modules/rxjs/internal/Observable.js
- /workspace/xplorer/docs/node_modules/rxjs/index.js
- /workspace/xplorer/docs/node_modules/wait-on/lib/wait-on.js
- /workspace/xplorer/docs/node_modules/@docusaurus/core/lib/webpack/plugins/WaitPlugin.js
- /workspace/xplorer/docs/node_modules/@docusaurus/core/lib/webpack/server.js
- /workspace/xplorer/docs/node_modules/@docusaurus/core/lib/commands/build.js
- /workspace/xplorer/docs/node_modules/@docusaurus/core/lib/index.js
- /workspace/xplorer/docs/node_modules/@docusaurus/core/bin/docusaurus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._resolveFilename (/workspace/xplorer/docs/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/workspace/xplorer/docs/node_modules/rxjs/internal/Observable.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspace/xplorer/docs/node_modules/rxjs/internal/Observable.js',
    '/workspace/xplorer/docs/node_modules/rxjs/index.js',
    '/workspace/xplorer/docs/node_modules/wait-on/lib/wait-on.js',
    '/workspace/xplorer/docs/node_modules/@docusaurus/core/lib/webpack/plugins/WaitPlugin.js',
    '/workspace/xplorer/docs/node_modules/@docusaurus/core/lib/webpack/server.js',
    '/workspace/xplorer/docs/node_modules/@docusaurus/core/lib/commands/build.js',
    '/workspace/xplorer/docs/node_modules/@docusaurus/core/lib/index.js',
    '/workspace/xplorer/docs/node_modules/@docusaurus/core/bin/docusaurus.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ 
```

### Steps To Reproduce

Pop up a Gitpod Workspace via the README and see the console logs, it misses some commands.

### Expected behavior

Supposed to not miss the commands as well as be successful since it has ALL of the dependencies inside the Docker image(yeah it runs on Docker images hosted on GKE)

### Xplorer Version

d9e451051bd8defe555045f17d038700a6ef7b3f

### Operating System Version

Gitpod's Ubuntu 20.04.2

### Additional Information

If you allow, I might be able to fix this.

**Comment by im-coder-lg** [comment]
To make _everybody_ clear, I am posting Neofetch results and Xplorer's About page results here. For the people who don't know Neofetch, it is a command to show your system info. And it shows everything.
Neofetch:
```zsh
➜  xplorer git:(im-coder-lg-gp-error-fixes) neofetch
            .-/+oossssoo+/-.
        `:+ssssssssssssssssss+:`
      -+ssssssssssssssssssyyssss+-
    .ossssssssssssssssssdMMMNysssso.
   /ssssssssssshdmmNNmmyNMMMMhssssss/
  +ssssssssshmydMMMMMMMNddddyssssssss+
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
+sssshhhyNMMNyssssssssssssyNMMMysssssss+
ossyNMMMNyMMhsssssssssssssshmmmhssssssso
ossyNMMMNyMMhsssssssssssssshmmmhssssssso
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   gitpod@ws-d1305e0a-5033-4805-a05c-6876c90d2555 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   ---------------------------------------------- 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    OS: Ubuntu 20.04.2 LTS x86_64 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Host: Google Compute Engine 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      Kernel: 5.4.0-1051-gke 
    .ossssssssssssssssssdMMMNysssso.       Uptime: 17 hours, 42 mins 
      -+sssssssssssssssssyyyssss+-         Packages: 729 (dpkg), 3 (brew) 
        `:+ssssssssssssssssss+:`           Shell: bash 5.0.17 
            .-/+oossssoo+/-.               Theme: Adwaita [GTK3] 
                                           Icons: Adwaita [GTK3] 
                                           Terminal: vscode 
                                           CPU: Intel Xeon (16) @ 2.800GHz 
                                           Memory: 22476MiB / 64319MiB 
➜  xplorer git:(im-coder-lg-gp-error-fixes) 
```
Xplorer's result taken from noVNC:
![image](https://user-images.githubusercontent.com/76845820/135981104-ae98322e-f39a-40c8-a97a-1f4535c8541b.png)

**Comment by im-coder-lg** [comment]
No use in fixing this. Gitpod might've accelerated on this. Closing
